version: "3"

services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - database
        ports:
            - "8000:80"
        environment:
            PMA_HOST: database
    database:
        image: mariadb:10.9.5
        volumes:
            - ./db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
