version: "3.8"

services:
    nginx:
        image: nginx:latest
        container_name: nginx_server
        ports:
            - "5743:80"
        volumes:
            - ./src:/usr/share/nginx/html:ro
        restart: unless-stopped
