import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { Navigation } from "@/app/components/navigation";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
    variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
    title: "Task-Liste",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="de">
            <body className={`${plusJakartaSans.className} antialiased w-screen h-screen flex`}>
                <aside className="bg-[repeating-linear-gradient(45deg,_var(--border-color),_var(--border-color)_var(--border-width),_transparent_var(--border-width),_transparent_10px)] w-fit h-screen flex p-3 border-r-(length:--border-width) border-(--border-color)">
                    <Navigation />
                </aside>
                {children}
            </body>
        </html>
    );
}
