USE Zoo;

CREATE TABLE Tierhaus (
    TierhausID INT AUTO_INCREMENT PRIMARY KEY,
    Bezeichnung VARCHAR(255) NOT NULL
);

CREATE TABLE TierArt (
    TierArtID INT AUTO_INCREMENT PRIMARY KEY,
    ArtBezeichnung VARCHAR(255) NOT NULL
);

CREATE TABLE ZooTier (
    ZooTierID INT AUTO_INCREMENT PRIMARY KEY,
    TierName VARCHAR(255) NOT NULL,
    TierAlter INT NOT NULL,
    ImZooSeit DATE NOT NULL,
    TierhausID INT NOT NULL,
    TierArtID INT NOT NULL,
    FOREIGN KEY (TierhausID) REFERENCES Tierhaus(TierhausID) ON DELETE CASCADE,
    FOREIGN KEY (TierArtID) REFERENCES TierArt(TierArtID) ON DELETE CASCADE
);

CREATE TABLE Pfleger (
    PflegerID INT AUTO_INCREMENT PRIMARY KEY,
    Vorname VARCHAR(255) NOT NULL,
    Nachname VARCHAR(255) NOT NULL
);

CREATE TABLE PflegerZuTier (
    ZooTierID INT NOT NULL,
    PflegerID INT NOT NULL,
    PRIMARY KEY (ZooTierID, PflegerID),
    FOREIGN KEY (ZooTierID) REFERENCES ZooTier(ZooTierID) ON DELETE CASCADE,
    FOREIGN KEY (PflegerID) REFERENCES Pfleger(PflegerID) ON DELETE CASCADE
);